#
# Your Crowdin credentials
#
project_id: '273870'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'

base_path: '.'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true

# See Yaml anchors: https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/
languages_mapping: &languages_mapping
  locale:
    'es-ES': 'es-ES'
    'fr': 'fr'
    'ja': 'ja'
    'pt-BR': 'pt-BR'
    'ro': 'ro'
    'ru': 'ru'
    'uk': 'uk'
    'zh-CN': 'zh-Hans'

#
# Files configuration
# see https://support.crowdin.com/configuration-file/
#
files: [
    # JSON translation files
    {
      source: '/i18n/en/**/*',
      translation: '/i18n/%two_letters_code%/**/%original_file_name%',
    },
    # Docs Markdown files
    {
      source: '/docs/**/*',
      translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
      ignore: ['/docs/**/fiddles', '/docs/**/images'],
    },
    # Blog Markdown files
    {
      source: '/blog/**/*',
      translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%',
    },
  ]
